package discovery

import (
	"context"
	"fmt"
	"maps"
	"os"
	"regexp"
	"slices"

	"github.com/ContainerHive/ContainerHive/internal/tagrange"
	"github.com/ContainerHive/ContainerHive/pkg/model"
)

// ociTagPattern mirrors internal/tagrange.ociTagPattern; duplicated here
// (rather than exported from tagrange) since it's only needed to validate
// static tags aren't accidentally shadowed by a malformed generated one -
// tagrange.GenerateTags already validates every tag it renders.
var ociTagPattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$`)

// resolveTagRanges expands every image's tag_ranges into concrete tags and
// merges them into that image's Tags map, in sorted image-identifier order
// so errors and logs are deterministic. It is a no-op - no cache is
// constructed, no source is touched - for a project where no image
// declares tag_ranges, which keeps every existing discovery call hermetic.
func resolveTagRanges(ctx context.Context, images map[string]*model.Image, hiveConfig *model.HiveProjectConfig, projectRoot string, opts *discoverOptions) error {
	if !anyTagRanges(images) {
		return nil
	}

	resolver := opts.resolver
	if resolver == nil {
		cacheDir, err := tagrange.ResolveCacheDir(os.Getenv(tagrange.CacheDirEnvVar), hiveConfig.CacheDir, projectRoot)
		if err != nil {
			return fmt.Errorf("failed to resolve tag_ranges cache directory: %w", err)
		}
		resolver = tagrange.NewResolver(tagrange.NewCache(cacheDir), nil)
	}

	for _, identifier := range slices.Sorted(maps.Keys(images)) {
		img := images[identifier]
		if len(img.TagRanges) == 0 {
			continue
		}
		generated, err := resolver.ResolveImage(ctx, img.Name, img.TagRanges)
		if err != nil {
			return fmt.Errorf("image %q: %w", img.Identifier, err)
		}
		if err := mergeGeneratedTags(img, generated); err != nil {
			return fmt.Errorf("image %q: %w", img.Identifier, err)
		}
	}
	return nil
}

func anyTagRanges(images map[string]*model.Image) bool {
	for _, img := range images {
		if len(img.TagRanges) > 0 {
			return true
		}
	}
	return false
}

// mergeGeneratedTags merges tag_ranges output into img.Tags, enforcing the
// collision rules: a static tag always wins over a generated one of the
// same name (the escape hatch for pinning); two different ranges producing
// the same name is a hard error (no defensible winner); and a generated
// name that collides with another tag's variant-suffixed form is a hard
// error, since that collision is otherwise invisible until a build fails.
func mergeGeneratedTags(img *model.Image, generated []tagrange.GeneratedTag) error {
	seenFrom := make(map[string]string, len(generated)) // tag name -> generating range's tag_name template

	for _, g := range generated {
		if !ociTagPattern.MatchString(g.Name) {
			return fmt.Errorf("generated tag %q is not a valid OCI tag", g.Name)
		}
		if existing, ok := img.Tags[g.Name]; ok && existing.GeneratedFrom == "" {
			continue // static tag wins; skip the generated one silently by design
		}
		if from, dup := seenFrom[g.Name]; dup && from != g.Range {
			return fmt.Errorf("tag %q is generated by more than one tag_range (%q and %q)", g.Name, from, g.Range)
		}
		if collidesWithVariantTag(img, g.Name) {
			return fmt.Errorf("generated tag %q collides with another tag's variant-suffixed form", g.Name)
		}
		seenFrom[g.Name] = g.Range

		img.Tags[g.Name] = &model.Tag{
			Name:          g.Name,
			Versions:      g.Versions,
			BuildArgs:     g.BuildArgs,
			Labels:        g.Labels,
			IsPrerelease:  g.IsPrerelease,
			GeneratedFrom: g.Range,
		}
	}
	return nil
}

// collidesWithVariantTag reports whether name equals some other tag's name
// plus a variant suffix - a collision that otherwise stays invisible until
// a build tries to produce two different images under the same tag.
func collidesWithVariantTag(img *model.Image, name string) bool {
	for tagName := range img.Tags {
		if tagName == name {
			continue
		}
		for _, variant := range img.Variants {
			if tagName+variant.TagSuffix == name {
				return true
			}
		}
	}
	return false
}
