import { Link } from 'react-router-dom'

function About() {
  return (
    <div className="container">
      <Link to="/" className="back-link">← Back to Gallery</Link>
      <div className="description-panel">
        <p>This report was generated by <a href="https://github.com/timo-reymann/container-hive" target="_blank" rel="noopener noreferrer" className="header-link">ContainerHive</a>, a CLI tool for creating container image reports. <a href="https://github.com/timo-reymann/container-hive" target="_blank" rel="noopener noreferrer" className="header-link">Check it out on GitHub →</a></p>
      </div>
      <div className="section">
        <h2>Why this report?</h2>
        <p>Container registries typically offer web interfaces, but they can be overwhelming when you just need a quick overview of your images. This report provides a simple, single-file HTML view that you can:</p>
        <ul>
          <li>Share easily via email or file transfer</li>
          <li>Host on any static file server</li>
          <li>Keep as a snapshot for documentation purposes</li>
        </ul>
        <p>This is a complement to registry UIs, not a replacement. For pushing, pulling, and managing images, use your registry's interface or tools like <code>docker</code> and <code>podman</code>.</p>
      </div>
    </div>
  )
}

export default About
