//go:build ignore

package main

import (
	"fmt"
	"log/slog"
	"os"
	"strings"
)

const (
	goModPath    = "go.mod"
	buildkitMod  = "github.com/moby/buildkit"
	outputPath   = "internal/buildkit/version_generated.go"
	outputHeader = `// Code generated by tools/generate-buildkit-version.go; DO NOT EDIT.

package buildkit

// Version is the BuildKit module version from go.mod.
const Version = %q
`
)

func main() {
	slog.Info("Generating BuildKit version from go.mod...")

	data, err := os.ReadFile(goModPath)
	if err != nil {
		slog.Error("Failed to read go.mod", "path", goModPath, "error", err)
		os.Exit(1)
	}

	version := ""
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, buildkitMod+" ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				version = parts[1]
			}
			break
		}
	}

	if version == "" {
		slog.Error("Could not find module in go.mod", "module", buildkitMod, "path", goModPath)
		os.Exit(1)
	}

	slog.Info("Found BuildKit version", "version", version)

	content := fmt.Sprintf(outputHeader, version)
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		slog.Error("Failed to write output", "path", outputPath, "error", err)
		os.Exit(1)
	}

	slog.Info("Wrote output", "path", outputPath)
}
