//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"strings"
)

const (
	goModPath    = "go.mod"
	buildkitMod  = "github.com/moby/buildkit"
	outputPath   = "internal/buildkit/version_generated.go"
	outputHeader = `// Code generated by tools/generate-buildkit-version.go; DO NOT EDIT.

package buildkit

// Version is the BuildKit module version from go.mod.
const Version = %q
`
)

func main() {
	log.Println("Generating BuildKit version from go.mod...")

	data, err := os.ReadFile(goModPath)
	if err != nil {
		log.Fatalf("failed to read %s: %v", goModPath, err)
	}

	version := ""
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, buildkitMod+" ") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				version = parts[1]
			}
			break
		}
	}

	if version == "" {
		log.Fatalf("could not find %s in %s", buildkitMod, goModPath)
	}

	log.Printf("Found BuildKit version: %s", version)

	content := fmt.Sprintf(outputHeader, version)
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		log.Fatalf("failed to write %s: %v", outputPath, err)
	}

	log.Printf("Wrote %s", outputPath)
}
