nav:
  - index.md
  - installation.md
  - usage
  - configuration
  - how-it-works
  - Development:
      - development/*.md
      - Architecture Decision Records:
          - adr/*.md

ignore:
  - adr/000-TEMPLATE.md
