site_name: ContainerHive
site_url: https://container-hive.timo-reymann.de
site_description: ContainerHive - Managing container base and library images has never been easier
site_author: Timo Reymann

markdown_extensions:
  - pymdownx.tabbed:
      alternate: true

plugins:
  - awesome-pages
  - search