name: Trigger Update Test Project

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  trigger-circleci:
    if: >-
      (github.event.action == 'labeled' && github.event.label.name == 'update-test-project') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'update-test-project'))
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        run: |
          curl -s -X POST "https://circleci.com/api/v2/project/gh/timo-reymann/ContainerHive/pipeline" \
            -H "Circle-Token: ${CIRCLECI_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "'"${GITHUB_HEAD_REF}"'",
              "parameters": {
                "update-test-project": true
              }
            }'
        env:
          CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}